# Generated by Django 3.1.6 on 2021-03-16 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_and_lastname', models.CharField(max_length=250, unique=True, verbose_name='Name and lastname')),
                ('country', models.CharField(blank=True, default='', max_length=70, verbose_name='Country')),
                ('city', models.CharField(blank=True, default='', max_length=70, verbose_name='City')),
                ('street', models.CharField(blank=True, default='', max_length=70, verbose_name='Street')),
                ('url', models.URLField(blank=True, default='', verbose_name='Url')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone number')),
                ('picture', models.URLField(blank=True, default='', verbose_name='Picture')),
            ],
        ),
    ]
