# Generated by Django 3.1.6 on 2021-03-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210318_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='lastname',
            field=models.CharField(max_length=70, null=True, verbose_name='Lastname'),
        ),
        migrations.AddField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=70, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Picture'),
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together={('name', 'lastname')},
        ),
        migrations.RemoveField(
            model_name='person',
            name='name_and_lastname',
        ),
    ]
